gamecollector/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('about/',views.about, name='about'),
    path('games/',views.games_index, name='index'),
    path('games/<int:game_id>/', views.games_detail, name='detail'),
    path('games/create/', views.GameCreate.as_view(), name='games_create'),
    path('games/<int:pk>/update/', views.GameUpdate.as_view(), name='games_update'),
    path('games/<int:pk>/delete/', views.GameDelete.as_view(), name='games_delete'),
    path('games/<int:game_id>/add_expansion/', views.add_expansion, name='add_expansion'),
    path('games/<int:game_id>/add_photo/', views.add_photo, name='add_photo'),
    path('games/<int:game_id>/assoc_player/<int:player_id>/', views.assoc_player, name='assoc_player'),
    path('players/', views.PlayerList.as_view(), name='players_index'),
    path('players/<int:pk>/', views.PlayerDetail.as_view(), name='players_detail'),
    path('players/create/', views.PlayerCreate.as_view(), name='players_create'),
    path('players/<int:pk>/update/', views.PlayerUpdate.as_view(), name='players_update'),
    path('players/<int:pk>/delete/', views.PlayerDelete.as_view(), name='players_delete'),
    path('accounts/signup', views.signup, name='signup'),
]

main_app/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User

class Player(models.Model):
    name = models.CharField(max_length=50)
    platform = models.CharField(max_length=50)

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('players_detail', kwargs={'pk': self.id})

class Game(models.Model):
    title = models.CharField(max_length=100)
    platform = models.CharField(max_length=100)
    description = models.TextField(max_length=250)
    relyear = models.IntegerField()
    players = models.ManyToManyField(Player)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('detail', kwargs={'game_id': self.id})

class Expansion(models.Model):
    extitle = models.CharField(max_length=100)
    rely = models.IntegerField()

    game = models.ForeignKey(Game, on_delete=models.CASCADE)


class Photo(models.Model):
    url = models.CharField(max_length=200)
    game = models.ForeignKey(Game, on_delete=models.CASCADE)

    def __str__(self):
        return f"Photo for game_id: {self.game_id} @{self.url}"

main_app/forms.py
from django.forms import ModelForm
from .models import Expansion

class ExpansionForm(ModelForm):
    class Meta:
        model = Expansion
        fields = ['extitle', 'rely']

main_app/views.py
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, DetailView
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Game, Player
from .forms import ExpansionForm

S3_BASE_URL = 'https://s3.us-east-2.amazonaws.com/'
BUCKET = 'gamecollector2'

import uuid
import boto3
from .models import Game, Player, Photo



def home(request):
    return render(request, 'home.html')

def about(request):
    return render(request, 'about.html')

@login_required
def games_index(request):
    games = Game.objects.filter(user=request.user)
    return render(request, 'games/index.html', {'games': games})
@login_required
def games_detail(request, game_id):
    game = Game.objects.get(id=game_id)
    players_game_doesnt_have = Player.objects.exclude(id__in = game.players.all().values_list('id'))
    expansion_form = ExpansionForm()
    return render(request, 'games/detail.html', {'game': game, 'expansion_form': expansion_form, 'players': players_game_doesnt_have})
@login_required
def add_expansion(request, game_id):
    form = ExpansionForm(request.POST)
    if form.is_valid():
        new_expansion = form.save(commit=False)
        new_expansion.game_id = game_id
        new_expansion.save()
    return redirect('detail', game_id=game_id)
@login_required
def assoc_player(request, game_id, player_id):
    Game.objects.get(id=game_id).players.add(player_id)
    return redirect('detail', game_id=game_id)
@login_required
def add_photo(request, game_id):
    
    photo_file = request.FILES.get('photo-file', None)
    if photo_file:
        s3 = boto3.client('s3')
        
        key = uuid.uuid4().hex[:6] + photo_file.name[photo_file.name.rfind('.'):]
        
        try:
            s3.upload_fileobj(photo_file, BUCKET, key)
            
            url = f"{S3_BASE_URL}{BUCKET}/{key}"
            
            photo = Photo(url=url, game_id=game_id)
            photo.save()
        except:
            print('An error occurred uploading file to S3')
    return redirect('detail', game_id=game_id)


def signup(request):
  error_message = ''
  if request.method == 'POST':
  
    form = UserCreationForm(request.POST)
    if form.is_valid():
      
      user = form.save()
      
      login(request, user)
      return redirect('index')
    else:
      error_message = 'Invalid sign up - try again'
 
  form = UserCreationForm()
  context = {'form': form, 'error_message': error_message}
  return render(request, 'registration/signup.html', context)

class GameCreate(LoginRequiredMixin, CreateView):
    model = Game
    fields = ['title','platform', 'description', 'relyear']
    success_url = '/games/'

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

class GameUpdate(LoginRequiredMixin, UpdateView):
    model = Game
    fields = ['platform', 'description', 'relyear']

class GameDelete(LoginRequiredMixin, DeleteView):
    model = Game
    success_url = '/games/'

class PlayerList(LoginRequiredMixin, ListView):
    model = Player

class PlayerDetail(LoginRequiredMixin, DetailView):
    model= Player

class PlayerCreate(LoginRequiredMixin, CreateView):
    model = Player
    fields = '__all__'

class PlayerUpdate(LoginRequiredMixin, UpdateView):
    model = Player
    fields = '__all__'

class PlayerDelete(LoginRequiredMixin, DeleteView):
    model = Player
    success_url = '/players/'

main_app/templates/about.html
{% extends 'base.html' %}
{% block content %}

<h1>About the Game Collector</h1>
<hr />
<p>I am the Game Collector!</p>

{% endblock %}

main_app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Game Collector</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
  <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
</head>
<body>
  <header class="navbar-fixed">
    <nav>
      <div class="nav-wrapper">
        <ul>
          <li><a href="/" class="left brand-logo">&nbsp;&nbsp;GameCollector</a></li>
        </ul>
        <ul class="right">
          <li><a href="{% url 'about' %}">About</a></li>
          {% if user.is_authenticated %}
            <li><a href="{% url 'players_create' %}">Add a Player</a></li>
            <li><a href="{% url 'players_index' %}">View all Players</a></li>
            <li><a href="{% url 'games_create' %}">Add a Game</a></li>
            <li><a href="{% url 'index' %}">View All My Games</a></li>
            <li><a href="{% url 'logout' %}">Log Out</a></li>
          {% else %}
            <li><a href="{% url 'signup' %}">Sign Up</a></li>
            <li><a href="{% url 'login' %}">Log In</a></li>
          {% endif %}
        </ul>
      </div>
    </nav>
  </header>
  <main class="container">
    {% block content %}
    {% endblock %}
  </main>
  <footer class="page-footer">
    <div class="right">All Rights Reserved, &copy; 2019 Game Collector &nbsp;</div>
  </footer>
</body>
</html>

main_app/templates/games/detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Game Details</h1>

<div class="row">
  <div class="col s6">
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ game.title }}</span>
        <p>Platform: {{ game.platform }}</p>
        <p>Description: {{ game.description }}</p>
        {% if game.relyear > 0 %}
          <p>Release Year: {{ game.relyear }}</p>
        {% else %}
          <p>Release Year: 2000's</p>
        {% endif %}
      </div>
      <div class="card-action">
        <a href="{% url 'games_update' game.id %}">Edit</a>
        <a href="{% url 'games_delete' game.id %}">Delete</a>
      </div>
    </div>

    {% for photo in game.photo_set.all %}
    <img class="responsive-img card-panel" src="{{photo.url}}">
  {% empty %}
    <div class="card-panel teal-text center-align">No Photos Uploaded</div>
  {% endfor %}

  <form action="{% url 'add_photo' game.id %}" enctype="multipart/form-data" method="POST" class="card-panel">
    {% csrf_token %}
    <input type="file" name="photo-file">
    <br><br>
    <input type="submit" class="btn" value="Upload Photo">
</form>

  </div>
  <div class="col s6">

    <form action= "{% url 'add_expansion' game.id %}" method="post">
      {% csrf_token %}
      {{ expansion_form.as_p }}
      <input type="submit" class="btn" value="Add Expansion">
    </form>

    <table class="striped">
      <thead>
        <tr><th>Expansion Packs</th><th>Release Year</th></tr>
      </thead>
      <tbody>
        {% for expansion in game.expansion_set.all %}
          <tr>
            <td>{{expansion.extitle}}</td>
            <td>{{expansion.rely}}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>

<hr>
<div class="row">
  <div class="col s6">
    <h3>Players that have played {{ game.title }}</h3>
    {% if game.players.count %}
      {% for player in game.players.all %}
        <div class="card">
          <div class="card-content">
            <span class="card-title">
               {{ player.name }}
            </span>
          </div>
        </div>
      {% endfor %}
    {% else %}
      <h5>No Players Yet :(</h5>
    {% endif %}
  </div>

  <div class="col s6">
    <h3>Available Players</h3>
    {% if players.count %}
      {% for player in players.all %}
        <div class="card">
          <div class="card-content">
            <span class="card-title">
               {{ player.name }}
            </span>
          </div>
          <div class="card-action">
            <form action="{% url 'assoc_player' game.id player.id %}" method="post">
              {% csrf_token %}
              <button type="submit" class="btn">Add</button>
            </form>
          </div>
        </div>
      {% endfor %}
    {% else %}
      <h5>{{game.title}} Already Has All Players Available</h5>
    {% endif %}
  </div>

{% endblock %}

main_app/templates/games/index.html
{% extends 'base.html' %}
{% block content %}

<h1>Game List</h1>

{% for game in games %}
 <a href="{% url 'detail' game.id %}">
  <div class="card">
    <div class="card-content">
      <span class="card-title">{{ game.title }}</span>
      <p>Platform: {{ game.platform }}</p>
      <p>Description: {{ game.description }}</p>
      {% if game.relyear > 0 %}
        <p>Release Year: {{ game.relyear }}</p>
      {% else %}
        <p>Release Year: 2000's</p>
      {% endif %}
    </div>
  </div>
</a>
{% endfor %}

{% endblock %}

main_app/templates/home.html
{% extends 'base.html' %}
{% block content %}

<h1>Home</h1>

{% endblock %}

main_app/templates/main_app/game_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Game</h1>

  <h4>Are you sure you want to delete <span class="teal-text">{{ object.title }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'detail' game.id %}">Cancel</a>
  </form>
{% endblock %}

main_app/templates/main_app/game_form.html
{% extends 'base.html' %}

{% block content %}

{% if object %}
    <h1>Edit <span class="teal-text">{{object.title}}</span></h1>
  {% else %}
    <h1>Add Game</h1>
  {% endif %}
  <!-- Leaving the action empty makes the form post to the same url used to display it -->
  <form action="" method="post">
    <!-- Django requires the following for security purposes -->
    {% csrf_token %}
    <table>
      <!-- Render the inputs inside of <tr>s & <td>s -->
      {{ form.as_table }}
    </table>
    <input type="submit" value="Submit!" class="btn">
  </form>
{% endblock %}

main_app/templates/main_app/player_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Player</h1>

  <h4>Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'players_detail' object.id %}">Cancel</a>
  </form>
{% endblock %}

main_app/templates/main_app/player_detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Player Details</h1>

<div class="row">
  <div class="col s6 col-offset-3">
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ player.name }}</span>
        <p>Platform: {{ player.platform }}</p>
      </div>
      <div class="card-action">
        <a href="{% url 'players_update' player.id %}">Edit</a>
        <a href="{% url 'players_delete' player.id %}">Delete</a>
      </div>
    </div>
  </div>
</div>
{% endblock %}

main_app/templates/main_app/player_form.html
{% extends 'base.html' %}

{% block content %}
  {% if object %}
    <h1>Edit <span class="teal-text">{{object.name}}</span></h1>
  {% else %}
    <h1>Add Player</h1>
  {% endif %}
  <!-- Leaving the action empty makes the form post to the same url used to display it -->
  <form action="" method="post">
    <!-- Django requires the following for security purposes -->
    {% csrf_token %}
    <table>
      <!-- Render the inputs inside of <tr>s & <td>s -->
      {{ form.as_table }}
    </table>
    <input type="submit" value="Submit!" class="btn">
  </form>
{% endblock %}

main_app/templates/main_app/player_list.html
{% extends 'base.html' %}
{% block content %}

<h1>Player List</h1>

{% for player in player_list %}
  <a href="{% url 'players_detail' player.id %}">
    <div class="card">
        <div class="card-content">
            <span class="card-title">{{ player.name }}</span>
            <p>Platfrom: {{ player.platform }}</p>
        </div>
    </div>
  </a>
{% endfor %}

{% endblock %}